# Generated by Django 4.2.7 on 2023-11-23 14:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.PositiveBigIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Стоимость')),
                ('label', models.TextField(verbose_name='Вопрос')),
                ('hint', models.TextField(verbose_name='Подсказка')),
                ('answer1', models.TextField(verbose_name='Ответ 1')),
                ('answer2', models.TextField(verbose_name='Ответ 2')),
                ('answer3', models.TextField(verbose_name='Ответ 3')),
                ('answer4', models.TextField(verbose_name='Ответ 4')),
                ('correct', models.CharField(max_length=4, verbose_name='Верные ответы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quiz', verbose_name='Игра'),
        ),
    ]
