# Generated by Django 5.0.1 on 2024-01-09 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_team_quiz_alter_quiz_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quiz'),
        ),
    ]
