# Generated by Django 5.0.1 on 2024-02-16 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_quiz_public_alter_quiz_owner_alter_team_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
    ]
